# fly.toml file generated for office-server on 2023-04-12T13:30:09+01:00

app = "office-server"
kill_signal = "SIGTERM"
primary_region = "lhr"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "office-server.fly.dev"
  PORT = "8080"
